### ISSUE TITLE
Enable testing multiple requests in a single test

### ISSUE THREAD

**Issue by chrislawlor** [chrislawlor/classify-server#3]
The `get_foursquare_category` function is designed to first hit Foursquare's "match" intent, then hit the "checkin" intent if a direct match wasn't found. See https://developer.foursquare.com/docs/api/venues/search for more information on the Foursquare search API.

Testing these functions requires mocking responses from the Foursquare API. Currently, there is
a very simple `MockClient`, which is given response data when instantiated. It will always return the same `MockResponse` object, to any `get` call. This makes it unsuitable for cases where we need to test how a function handles multiple, different responses to the API.

Enhance the `MockClient` class by allowing test code to load multiple responses. Responses will need to be stored in such a way that the response matches the URL passed to `get` - probably a simple dictionary will suffice. Usage could look something like this:

```
client = MockClient()
client.add_response(some_url, failed_response_data, response_status_code=400)
client.add_response(another_url, success_response_data)

response = client.get(some_url)
assert response == failed_response_data
assert response.status == 400

response = client.get(another_url)
assert response.status == 200
```

**Comment by shepherdjay** [comment]
Hey, @chrislawlor if no one is started I'm happy to begin working on this - looks straightforward.
